//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("BP Exporter")]
[assembly: System.Reflection.AssemblyDescription("Baseprotect Exporter Tool")]
[assembly: System.Reflection.AssemblyCompany("Baseprotect GmbH")]
[assembly: System.Reflection.AssemblyProduct("product")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2009")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("88812638-9547-4480-9bf4-4fe25103b35c")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.21")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.21")]


